name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
    steps:
      # Checkout the Repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      # Install .NET
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # Install NuGet Dependencies
      - name: Install dependencies
        run: dotnet restore
         
      # Create Build
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/build
          
      # Upload as Job Artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: csgo-m4a1s-unbind
          path: ${{env.DOTNET_ROOT}}/build